## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
## 
##  http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
## 

> set daffodilVersion := "4.0.0"
> packageDaffodilBin
$ exists target/test-0.1-daffodil400.bin
> test
> clean

> set daffodilVersion := "3.11.0"
> packageDaffodilBin
$ exists target/test-0.1-daffodil3110.bin
> test
> clean

> set daffodilVersion := "3.10.0"
> packageDaffodilBin
$ exists target/test-0.1-daffodil3100.bin
> test
> clean

> set daffodilVersion := "3.9.0"
> packageDaffodilBin
$ exists target/test-0.1-daffodil390.bin
> test
> clean

> set daffodilVersion := "3.8.0"
> packageDaffodilBin
$ exists target/test-0.1-daffodil380.bin
> test
> clean

> set daffodilVersion := "3.7.0"
> packageDaffodilBin
$ exists target/test-0.1-daffodil370.bin
> test
> clean

> set daffodilVersion := "3.6.0"
> packageDaffodilBin
$ exists target/test-0.1-daffodil360.bin
> test
> clean

> set daffodilVersion := "3.5.0"
> packageDaffodilBin
$ exists target/test-0.1-daffodil350.bin
> test
> clean

> set daffodilVersion := "3.4.0"
> packageDaffodilBin
$ exists target/test-0.1-daffodil340.bin
> test
> clean

> set daffodilVersion := "3.3.0"
> packageDaffodilBin
$ exists target/test-0.1-daffodil330.bin
> test
> clean

> set daffodilVersion := "3.2.0"
> packageDaffodilBin
$ exists target/test-0.1-daffodil320.bin
> test
> clean
