## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
## 
##  http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
## 

# define a local file for publishing and resolving artifacts
> set every publishTo := Some(Resolver.file("file", new File("target/ivy-publish/")))
> set every resolvers := Seq("file" at new File("target/ivy-publish/").getAbsoluteFile.toURI.toString)

# publish all versions of the plugin
> plugin/publish

# test only 3.10.0 with the plugin
> schema/test

# test only 3.11.0 with the plugin
> schema_daffodil3110/test

# test only 4.0.0 with the plugin
> schema_daffodil400/test

# publish the schema and all versions of saved parsers
> schema/publish

# run bundle resource generators, which should copy the plugin and saved
# parsers to a "release" directory
> bundle/package
> bundle_daffodil3110/package
> bundle_daffodil400/package

$ exists bundle/target/release/test-plugin-0.1-daffodil400.jar
$ exists bundle/target/release/test-schema-0.1-daffodil400.bin

$ exists bundle/target/release/test-plugin-0.1-daffodil3100.jar
$ exists bundle/target/release/test-schema-0.1-daffodil3100.bin

$ exists bundle/target/release/test-plugin-0.1-daffodil3110.jar
$ exists bundle/target/release/test-schema-0.1-daffodil3110.bin
