## Licensed to the Apache Software Foundation (ASF) under one
## or more contributor license agreements.  See the NOTICE file
## distributed with this work for additional information
## regarding copyright ownership.  The ASF licenses this file
## to you under the Apache License, Version 2.0 (the
## "License"); you may not use this file except in compliance
## with the License.  You may obtain a copy of the License at
## 
##  http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing,
## software distributed under the License is distributed on an
## "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
## KIND, either express or implied.  See the License for the
## specific language governing permissions and limitations
## under the License.
## 

> packageDaffodilBin
$ exists target/test-0.1-daffodil3100.bin

$ absent target/daffodil3110/test-0.1-daffodil3110.bin
$ absent target/daffodil400/test-0.1-daffodil400.bin

> test_daffodil3110/packageDaffodilBin
$ exists target/daffodil3110/test-0.1-daffodil3110.bin

> test_daffodil400/packageDaffodilBin
$ exists target/daffodil400/test-0.1-daffodil400.bin

> clean
> set aggregate := true
> packageDaffodilBin

$ exists target/test-0.1-daffodil3100.bin
$ exists target/daffodil3110/test-0.1-daffodil3110.bin
$ exists target/daffodil400/test-0.1-daffodil400.bin

> clean
> set aggregate := false

> set publishTo := Some(Resolver.file("file", new File("target/ivy-publish/")))
> publish
$ exists target/ivy-publish/com/example/test/0.1/test-0.1.jar
$ exists target/ivy-publish/com/example/test/0.1/test-0.1-daffodil3100.bin
$ exists target/ivy-publish/com/example/test/0.1/test-0.1-daffodil3100.bin
$ exists target/ivy-publish/com/example/test/0.1/test-0.1-daffodil400.bin

> test
> test_daffodil3110/test
> test_daffodil400/test
